[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["export NODE_OPTIONS='--max-old-space-size=2048' && npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048" 