[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048" 